name: Deploy to github pages


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.4
    - name: make go build
      run: make build
    - name: Upload ./wasm/main.wasm file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: main.wasm
        path: ./wasm/main.wasm
        if-no-files-found: error


